package com.inversionesaraujo.api.model;

public enum Permission {
    CLIENTS_WATCH,
    CLIENTS_CREATE,
    CLIENTS_UPDATE,
    CLIENTES_DELETE,

    ROLES_WATCH,
    ROLES_CREATE,
    ROLES_UPDATE,
    ROLES_DELETE,

    PERMISSIONS_WATCH,

    EMPLOYEES_WATCH,
    EMPLOYEES_CREATE,
    EMPLOYEES_UPDATE,
    EMPLOYEES_DELETE,

    INVITRO_WATCH,
    INVITRO_CREATE,
    INVITRO_UPDATE,
    INVITRO_DELETE, 
    INVITRO_CHAT,

    TUBER_CREATE,
    TUBER_UPDATE,
    TUBER_DELETE,

    VARIETY_CREATE,
    VARIETY_UPDATE,
    VARIETY_DELETE,

    INVITRO_ITEM_CREATE,
    INVITRO_ITEM_UPDATE,
    INVITRO_ITEM_DELETE,
    
    INVITRO_ADVANCE_WATCH,
    INVITRO_ADVANCE_CREATE,
    INVITRO_ADVANCE_UPDATE,
    INVITRO_ADVANCE_DELETE,

    PRODUCTS_WATCH,
    PRODUCTS_CREATE,
    PRODUCTS_UPDATE,
    PRODUCTS_DELETE,
    PRODUCTS_BATCH_CREATE,

    PRODUCTS_CATEGORY_CREATE,
    PRODUCTS_CATEGORY_UPDATE,
    PRODUCTS_CATEGORY_DELETE,
    
    PRODUCTS_DISCOUNT_CREATE,
    PRODUCTS_DISCOUNT_UPDATE,
    PRODUCTS_DISCOUNT_DELETE,

    PRODUCTS_IMAGE_CREATE,
    PRODUCTS_IMAGE_DELETE,

    ORDERS_WATCH,
    ORDERS_CREATE,
    ORDERS_UPDATE,
    ORDERS_DELETE,
    ORDERS_CHAT,

    ORDERS_PRODUCTS_CREATE,
    ORDERS_PRODUCTS_UPDATE,
    ORDERS_PRODUCTS_DELETE,

    INVOICES_WATCH,
    INVOICES_CREATE,
    INVOICES_UPDATE,
    INVOICES_DELETE,

    INVOICES_ITEM_CREATE,
    INVOICES_ITEM_UPDATE,
    INVOICES_ITEM_DELETE,

    BANNERS_WATCH,
    BANNERS_CREATE,
    BANNERS_UPDATE,
    BANNERS_DELETE,

    BANNERS_ITEM_CREATE,
    BANNERS_ITEM_DELETE,
    
    WAREHOUSES_WATCH,
    WAREHOUSES_CREATE,
    WAREHOUSES_UPDATE,
    WAREHOUSES_DELETE,

    MESSAGES_WATCH,
    MESSAGES_DELETE,

    PROFITS_WATCH,

    EXPENSES_WATCH,
    EXPENSES_CREATE,
    EXPENSES_UPDATE,
    EXPENSES_DELETE,
}
